spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_lab03
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      query-timeout: 3

  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    cache: false

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml